version: '3.7'

services:
  app:
    image: ghcr.io/intersect-software/web-reactionz:main
    env_file:
      - .env
    ports:
      - '127.0.0.1:3000:3000'

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine

volumes:
  postgres:
