name: Build
on:
  push:
    branches: "main"
    tags:
      - "*"
  workflow_dispatch:
    inputs:
      version:
        description: "Version"
        type: number
        required: true

permissions:
  contents: read
  packages: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/intersect-software/web-reactionz
          tags: |
            type=ref,event=branch
            type=semver,pattern={{major}}.{{minor}}.{{patch}},value=${{ github.event.inputs.version }}
            type=semver,pattern={{major}}.{{minor}},value=${{ github.event.inputs.version }}
            type=semver,pattern={{major}},value=${{ github.event.inputs.version }}

      - name: Login to the GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            BUILD_ROOT_URL=${{ secrets.BUILD_ROOT_URL }}
            BUILD_SITE_ID=${{ secrets.BUILD_SITE_ID }}
            BUILD_ANALYTICS_URL=${{ secrets.BUILD_ANALYTICS_URL }}
            BUILD_ANALYTICS_SITE_ID=${{ secrets.BUILD_ANALYTICS_SITE_ID }}
